### PR TITLE
Fix #66. Make all touch events composed events

### LINKED ISSUE #66: Support Event.composed in Touch Events
The context: w3c/webcomponents#513

Could someone give me advice how we should update Touch Events specification so it considers Event.composed?

Is a Pull Request a recommended way to reflect the conclusion at w3c/webcomponents#513
?

### PR DESCRIPTION
**Pull request by hayatoito**
Regarding https://github.com/w3c/touch-events/pull/67, make all touch events composed events.

### CODE REVIEW

**Comment by patrickhlauke** [comment]
as I'm not completely au-fait with what composed events actually are/do, nor if there are any issues with a W3C spec referencing WHATWG (political or otherwise) ... @RByers, thoughts?

**Comment by RByers** [comment]
The clearest definition of composed seems to be in the note [here](https://github.com/WICG/IntersectionObserver/blob/gh-pages/explainer.md):

> True if event invokes listeners past a ShadowRoot node that is the root of its target attribute value, and false otherwise.

I think the general approach (of extending this spec and referring to the WHATWG DOM spec) is fine.  When / if we ever go to publish a CR spec we may need to replace the reference to a W3C version, but presumably by then the W3C fork will be updated to also define `composed`.

I have a couple questions / concerns with the overall approach though - I'll follow up on w3c/webcomponents#513 and circle back here.

**Comment by hayatoito** [comment]
Thank you for the review.

> When / if we ever go to publish a CR spec we may need to replace the reference to a W3C version, but presumably by then the W3C fork will be updated to also define composed.

I understand the concern. Actually, I thought the similar thing in creating the PR because it looks that most (all?) of W3C specification do not have a reference to a WHATWG Standard. It looks they try to avoid to have a reference to WHATWG. I am not 100% sure how we proceed in this case.

@annevk do you have any advice? Should I wait W3C version for incorporating `Event.composed` from WHATWG DOM?

If having a reference to WHATWG DOM is okay, I will try to make a PR for UIEvents at first here https://github.com/w3c/uievents/issues/89. After that, let me ask a merge of PR for Touch Events and Pointer Events, again.

**Comment by annevk** [comment]
There shouldn't be any issue referencing WHATWG documents. Happens all the time. I don't think anyone is maintaining the DOM fork either (which is annoying, since you have to know that is the case, it would be much easier if they just stopped copy-and-pasting without due process).

**Comment by hayatoito** [comment]
@annevk Thank you!

**Comment by hayatoito** [comment]
@RByers 

PR for UI events has been merged https://github.com/w3c/uievents/pull/91.
Could you review this PR now?

**Comment by RByers** [comment]
LGTM, thanks!

**Pull request merged**
