### PR TITLE
Update retargeting steps link

### LINKED ISSUE #134: Broken references in Touch Events - Level 2
While crawling [Touch Events - Level 2](https://w3c.github.io/touch-events/), the following links to other specifications were detected as pointing to non-existing anchors, which should be fixed:
* [ ] https://dom.spec.whatwg.org/#event-retargeting-steps

<sub>This issue was detected and reported semi-automatically by [Strudy](https://github.com/w3c/strudy/) based on data collected in [webref](https://github.com/w3c/webref/).</sub>

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes #134

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/touch-events/pull/135.html" title="Last updated on Jan 28, 2023, 12:03 AM UTC (312ab2c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/touch-events/135/7728b83...312ab2c.html" title="Last updated on Jan 28, 2023, 12:03 AM UTC (312ab2c)">Diff</a>

### CODE REVIEW

**Comment by patrickhlauke** [comment]
@annevk can I just check that this is the correct new location that the links should point to?

**Comment by annevk** [comment]
I'll check when we broke this ID. I'm sorry we did.

Having said that, you should probably not directly link to this algorithm but instead use the normal way to refer to algorithms in other specifications. That way https://dontcallmedom.github.io/webdex/ will also track it and I can more easily avoid breaking Touch Events going forward.

**Comment by annevk** [comment]
Okay, it seems this concept was intentionally removed in https://github.com/whatwg/dom/pull/585, but https://github.com/w3c/touch-events/issues/92 was never taken up by anyone.

So this probably doesn't work as-is. Instead Touch Events needs to build on top of event's touch target list.

And I see that @smaug---- suggested in the DOM PR that concept might need further tweaks.

**Comment by patrickhlauke** [comment]
touch events spec is pretty much on minimum life support at this point... so hoping for some small tweaks that at least mean things are not completely broken

**Comment by annevk** [comment]
I would add a big issue banner pointing to #92 in that case.

**Pull request merged**
