### PR TITLE
Merge v1-errata into master branch

### PR DESCRIPTION
**Pull request by RByers**
As discussed on [public-touchevents](https://lists.w3.org/Archives/Public/public-touchevents/2015Apr/0015.html) we've decided that we won't be able to publish the v1 changes as an 'errata' after all.  So merge the v1-arrata and touch event extensions note into "Touch Events - Level 2".

This directly copies the extensions into the v1-errata document.  I made one change: "Issue: Consider aligning with other "channels" and values from InkML" etc. as I think it's obsolete (it's highly unlikely that we'd add any additional properties to Touch at this point).

You can see the result [here](http://rawgit.com/RByers/touch-events/merged-v2/touchevents.html).

### CODE REVIEW

**Comment by patrickhlauke** [comment]
Wondering if it's worth also just renaming `touchevents.html`to just `index.html`, but otherwise this looks good to me in principle

**Comment by RByers** [comment]
Good question.  It's probably easiest to do that as a 2nd step if we want to.  I don't have a strong preference for use of index.html or not - either way seems to have it's own small advantages.

**Comment by patrickhlauke** [comment]
Additionally: should the text contain some small nod/reference to the fact that the TE extensions from http://www.w3.org/TR/touch-events-extensions/ have been rolled into this? Maybe just in the intro or references?

**Comment by RByers** [comment]
> Additionally: should the text contain some small nod/reference to the fact that the TE extensions from http://www.w3.org/TR/touch-events-extensions/ have been rolled into this? Maybe just in the intro or references?

Probably a good idea, thanks.  How's this for now (figured "status of this document" was probably the right place)?  We can continue to tweak the exact format after this lands (looks like we probably have other tweaks to make to reflect that this is a level 2 doc, but I'm not familiar enough with the normal process to know how best to do that.

**Comment by patrickhlauke** [comment]
LGTM for the moment, yup

**Comment by RByers** [comment]
Thanks.  Not hearing other feedback, I'm going to go ahead and merge this now to unblock other changes.

**Pull request merged**
